Test ID: network_failure_packet_drop_2
Test: network_failure_packet_drop
Iteration: 2
Start Time: 2024-11-15 14:35:23.579001
network_failure_packet_drop_2 - Exception: DistributedClient.__init__() got an unexpected keyword argument 'servers'
Result: FAIL
End Time: 2024-11-15 14:35:23.579023
