Test ID: single_server_failure_lock_held_7
Test: single_server_failure_lock_held
Iteration: 7
Start Time: 2024-11-15 14:35:23.582417
single_server_failure_lock_held_7 - Exception: DistributedClient.__init__() got an unexpected keyword argument 'servers'
Result: FAIL
End Time: 2024-11-15 14:35:23.582437
